<?php

namespace ApiV1Bundle\Repository;

/**
 * AgenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenteRepository extends ApiRepository
{
    /**
     * @return \Doctrine\ORM\EntityRepository
     */

    private function getRepository()
    {
        return $this->getEntityManager()->getRepository('ApiV1Bundle:Agente');
    }

    public function findAllPaginate($puntoAtencionId, $offset, $limit)
    {
        $query = $this->getRepository()->createQueryBuilder('a');

        $query
            ->leftJoin('a.ventanillaActual', 'v')
            ->where('a.puntoAtencion = :puntoAtencionId')
            ->setParameter('puntoAtencionId', $puntoAtencionId);

        $query->setFirstResult($offset);
        $query->setMaxResults($limit);
        $query->orderBy('a.id', 'ASC');
        return $query->getQuery()->getResult();
    }
}
