<?php

namespace ApiV1Bundle\Repository;

/**
 * AgenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenteRepository extends \Doctrine\ORM\EntityRepository
{
}
