<?php

namespace ApiV1Bundle\Repository;

/**
 * ColaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColaRepository extends \Doctrine\ORM\EntityRepository
{
}
