<?php

namespace ApiV1Bundle\Repository;

/**
 * PuntoAtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntoAtencionRepository extends \Doctrine\ORM\EntityRepository
{
}
