<?php

namespace ApiV1Bundle\Repository;

/**
 * PuntoAtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntoAtencionRepository extends ApiRepository
{

    /**
     * @return \Doctrine\ORM\EntityRepository
     */

    private function getRepository()
    {
        return $this->getEntityManager()->getRepository('ApiV1Bundle:PuntoAtencion');
    }
    
    public function findAllPaginate($offset, $limit)
    {

        $query = $this->getRepository()->createQueryBuilder('p');

        $query->select([
            'p.id',
            'p.nombre'
        ]);
 
        $query->setFirstResult($offset);
        $query->setMaxResults($limit);
        $query->orderBy('p.id', 'ASC');
        return $query->getQuery()->getResult();
    }
}
