<?php

namespace ApiV1Bundle\Repository;

/**
 * VentanillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentanillaRepository extends \Doctrine\ORM\EntityRepository
{
}
