# api specific parameters
parameters:
    integration:
     #   host: 'http://sntapi.hexacta.com:8008/api/v1.0'
        host: 'http://localhost:8080/api/v1.0'
        urls:
            turnos.fecha: '/turnos/fecha'
            turnos: '/turnos'