# api specific parameters
parameters:
    integration:
        host: '%snt_api_integration%'
        urls:
            turnos.fecha: '/turnos/fecha'
            turnos: '/turnos'
            turnos.buscar: '/turnos/buscar/codigo'