# api specific parameters
parameters:
    notificaciones:
        host: 'http://186.33.229.89/1.0'
        user: 'sistematurnos'
        pass: '>Q!D`"9zB}f`L<[R'
        token: 'ae35524801429b26e7bcd718ca01ca7b5c988788'
        from: 'snt@hexacta.com'
        subject: 'Sistema Nacional de Turnos'
        template: 'test004-sistematurnos'
        urls:
            auth: '/api-auth/token'
            templates: '/templates'
            template_test: '/templates/%s/preview'
            notifications: '/notifications'
            