parameters:

    # Services
    snc.services.general.class: ApiV1Bundle\ApplicationServices\SNCServices
    snc.services.security.class: ApiV1Bundle\ApplicationServices\SecurityServices
    snc.services.agente.class: ApiV1Bundle\ApplicationServices\AgenteServices
    snc.services.ventanilla.class: ApiV1Bundle\ApplicationServices\VentanillaServices

    # Repository    
    snc.repository.user.class: ApiV1Bundle\Repository\UserRepository
    snc.repository.agente.class: ApiV1Bundle\Repository\AgenteRepository
    snc.repository.ventanilla.class: ApiV1Bundle\Repository\VentanillaRepository
    snc.repository.cola.class: ApiV1Bundle\Repository\ColaRepository

    # Validators
    snc.validator.agente.class: ApiV1Bundle\Entity\Validator\AgenteValidator
    snc.validator.user.class: ApiV1Bundle\Entity\Validator\UserValidator
    snc.validator.ventanilla.class: ApiV1Bundle\Entity\Validator\VentanillaValidator
    
    # Security
    snc.helper.jwtoken.class: ApiV1Bundle\Helper\JWToken
    snc.security.builder.class: Lcobucci\JWT\Builder
    snc.security.parser.class: Lcobucci\JWT\Parser
    snc.security.validation.class: Lcobucci\JWT\ValidationData

services:
    
    ## SECURITY ##
    
    snc.security.builder:
        class: '%snc.security.builder.class%'
    
    snc.security.parser:
        class: '%snc.security.parser.class%'
        
    snc.security.validation:
        class: '%snc.security.validation.class%'
    
    snc.helper.jwtoken:
        class: '%snc.helper.jwtoken.class%'
        arguments: ['%secret%', '@snc.security.builder', '@snc.security.parser', '@snc.security.validation']
    
    ## REPOSITORIES ##

    snc.repository.user:
        class: '%snc.repository.user.class%'
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - ApiV1Bundle\Entity\User

    snc.repository.agente:
        class: '%snc.repository.agente.class%'
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - ApiV1Bundle\Entity\Agente

    snc.repository.ventanilla:
        class: '%snc.repository.ventanilla.class%'
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - ApiV1Bundle\Entity\Ventanilla

    snc.repository.cola:
        class: '%snc.repository.cola.class%'
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - ApiV1Bundle\Entity\Cola

    ### SERVICES ###

    snc.services.general:
        class: '%snc.services.general.class%'
        arguments: ['@service_container']
    
    snc.services.security:
        class: '%snc.services.security.class%'
        arguments: ['@service_container', '@snc.repository.user', '@security.password_encoder', '@snc.helper.jwtoken']

    snc.services.agente:
        class: '%snc.services.agente.class%'
        arguments: ['@service_container', '@snc.repository.agente', '@snc.validator.agente', '@snc.validator.user', '@snc.repository.ventanilla']

    snc.services.ventanilla:
        class: '%snc.services.ventanilla.class%'
        arguments: ['@service_container', '@snc.repository.ventanilla', '@snc.validator.ventanilla']

    ## VALIDATORS ##

    snc.validator.agente:
       class: '%snc.validator.agente.class%'

    snc.validator.ventanilla:
          class: '%snc.validator.ventanilla.class%'

    snc.validator.user:
       class: '%snc.validator.user.class%'
       arguments: ['@snc.repository.user']
